### ISSUE TITLE
unable to resolve @import paths in scss files.

### ISSUE THREAD

**Issue by hannadrehman** [yibn2008/fast-sass-loader#39]
because of poor performance in sass-loader i decided to switch to fast-sass-loader. but i am unable to make it work.
my build fails because it cannot resolve paths which were originally resolved by sass-loader. 
i am using `webpack 4`  and `AntdScssThemePlugin` 
here is a piece of code from my webpack config

```
   {
          test: /\.scss$/,
          use: [
            !isProd ? 'style-loader' : MiniCssExtractPlugin.loader,
            {
              loader: 'css-loader',
              options: {
                sourceMap: false,
                include: path.resolve(__dirname, '../', './src'),
              },
            },
            {
              loader: 'postcss-loader',
              options: {
                sourceMap: false,
                include: path.resolve(__dirname, '../', './src'),
                plugins() {
                  return [autoprefixer('last 2 versions', 'ie 10')];
                },
              },
            },
            AntdScssThemePlugin.themify({
              loader: 'sass-loader',
              options: {
                sourceMap: false,
                include: path.resolve(__dirname, '../', './src'),
                data: '@import "./src/Styles/themes/core";@import "./src/Styles/themes/anttheme";',
              },
            }),
          ],
        },
```
this loader works fine when i am using sass-loader. but same will fail if i switch to fast-sass-loader

```
   {
          test: /\.scss$/,
          use: [
            !isProd ? 'style-loader' : MiniCssExtractPlugin.loader,
            {
              loader: 'css-loader',
              options: {
                sourceMap: false,
                include: path.resolve(__dirname, '../', './src'),
              },
            },
            {
              loader: 'postcss-loader',
              options: {
                sourceMap: false,
                include: path.resolve(__dirname, '../', './src'),
                plugins() {
                  return [autoprefixer('last 2 versions', 'ie 10')];
                },
              },
            },
            AntdScssThemePlugin.themify({
              loader: 'fast-sass-loader',
              options: {
                sourceMap: false,
                include: path.resolve(__dirname, '../', './src'),
                data: '@import "./src/Styles/themes/core";@import "./src/Styles/themes/anttheme";',
              },
            }),
          ],
        },
```
here is the error which i get 
```
ERROR in ./src/App/Common/ErrorHandler/ErrorHandler.styles.scss (./node_modules/css-loader??ref--9-1!./node_modules/postcss-loader/lib??ref--9-2!./node_modules/fast-sass-loader/lib??ref--9-3!./src/App/Common/ErrorHandler/ErrorHandler.styles.scss)
Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
Error: import file cannot be resolved: "@import "./src/Styles/themes/core";" @/Users/akashtalreja/Hannad/Apps/front end project/client/src/App/Common/ErrorHandler/ErrorHandler.styles.scss
    at Object.importReplacer (/Users/akashtalreja/Hannad/Apps/front end project/client/node_modules/fast-sass-loader/lib/index.js:206:19)
    at importReplacer.throw (<anonymous>)
    at onRejected (/Users/akashtalreja/Hannad/Apps/front end project/client/node_modules/co/index.js:81:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
 @ ./src/App/Common/ErrorHandler/ErrorHandler.styles.scss 2:14-236 21:1-42:3 22:19-241
 @ ./src/App/Common/ErrorHandler/ErrorHandler.component.jsx
 @ ./src/App/Common/index.js
 @ ./src/App/Router/index.jsx
 @ ./src/App/Layout/index.jsx
 @ ./src/App/index.jsx
 @ ./src/App.hot.js
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://localhost:9000 (webpack)/hot/dev-server.js react-hot-loader/patch ./src/index.jsx
```

**Comment by yibn2008** [comment]
do you have any example repo to reproduce this?

**Comment by hannadrehman** [comment]
I can't put my code on git.. *company policy* 
I am not doing anything special. sass-loader works fine

**Comment by XavierLeTohic** [comment]
@yibn2008 any news about-it ? Same problem here.

**Comment by yoche2001** [comment]
@yibn2008 Same thing here… what a pity that its currently not usable. It looked very promising.

**Comment by yibn2008** [comment]
try `fast-sass-loader@1.4.7`, this issue should be fixed.

**Comment by AndrewBogdanovTSS** [comment]
I use `fast-sass-loader@1.5.0` and still reproduce this issue. Please, reopen

**Comment by yibn2008** [comment]
@AndrewBogdanovTSS please provide more detail

**Comment by AndrewBogdanovTSS** [comment]
@yibn2008 you can read the details here https://github.com/prashantpalikhe/nuxt-overclock/issues/1
But the gist of it is the same as for topicstarter - I have issues with importing files once switching from `sass-loader` to `fast-sass-loader`

**Comment by fredericpfisterer** [comment]
Facing same issue here with latest version. Please re-open. It's too bad cause the performance are amazing !

**Comment by pratikm23** [comment]
Any update on this issue. Facing same issue

**Comment by alon24** [comment]
I am facing this issue with imports too

**Comment by vitobotta** [comment]
Me too, I am trying to use this but get errors about imports. Has anyone found a solution in the meantime?

**Comment by RacerDelux** [comment]
I too am facing the same issue. Pitty.

**Comment by mao0613** [comment]
i have same issue when using fast-sass-loader@2.0.0

**Comment by jogo81** [comment]
same problem here, fast-sass-loader@2.0.0. Also tried older Versions. sass-loader works fine.

**Comment by molyholy** [comment]
Exact same issue. What does sass-loader do differently?
